"""Added fields for GitHub user data

Revision ID: 595977c1a17f
Revises: 
Create Date: 2024-10-02 17:59:06.967045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595977c1a17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('blog', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('public_repos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('profile_url', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['github_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profile_url')
        batch_op.drop_column('created_at')
        batch_op.drop_column('following')
        batch_op.drop_column('followers')
        batch_op.drop_column('public_repos')
        batch_op.drop_column('blog')
        batch_op.drop_column('location')
        batch_op.drop_column('company')
        batch_op.drop_column('bio')
        batch_op.drop_column('name')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('email')
        batch_op.drop_column('github_id')

    # ### end Alembic commands ###
