"""empty message

Revision ID: d25df9b09ee2
Revises: 595977c1a17f
Create Date: 2024-10-02 23:11:44.114132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd25df9b09ee2'
down_revision = '595977c1a17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('public_repos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_repos', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
