#!/bin/sh
echo "Running post-commit Python scripts..."

# Get a list of files committed in the last commit that match the naming pattern across all directories
last_commit_files=$(git diff-tree --no-commit-id --name-only -r HEAD | grep -E '(^|/)(\.env.*|creds.txt)$')

# Only run the decrypt script if there are matching files in the last commit
if [ -n "$last_commit_files" ]; then
    echo "Detected .env* or creds.txt files in the last commit. Running decryption script..."

    # Use a loop to pass each file to the Python decryption script individually
    echo "$last_commit_files" | while IFS= read -r file; do
        echo "Decrypting $file..."
        python_output=$(python git_commit_decrypt_secrets.py "$file")
        echo "$python_output"

        # Check for errors after each file
        if [ $? -ne 0 ]; then
            echo "Failed to decrypt file: $file"
            exit 1
        fi
    done

    echo "Decryption completed successfully for committed files."
else
    echo "No .env* or creds.txt files found in the last commit. Skipping decryption."
fi

exit 0
