start:
	yarn run dev --port 3000

lint:
	yarn lint

format:
	yarn format


## Docker Commands

start-docker:
	docker-compose up

clean-docker:
	docker-compose down --volumes --remove-orphans
	docker-compose build --no-cache
	docker-compose up