name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$SUPER_SECRET"